Su Doku (Japanese meaning number place) is the name given to a popular puzzle concept. Its origin is unclear, but credit must be attributed to Leonhard Euler who invented a similar, and much more difficult, puzzle idea called Latin Squares. The objective of Su Doku puzzles, however, is to replace the blanks (or zeros) in a 9 by 9 grid in such that each row, column, and 3 by 3 box contains each of the digits 1 to 9. Below is an example of a typical starting puzzle grid and its solution grid.

A well constructed Su Doku puzzle has a unique solution and can be solved by logic, although it may be necessary to employ "guess and test" methods in order to eliminate options (there is much contested opinion over this). The complexity of the search determines the difficulty of the puzzle; the example above is considered easy because it can be solved by straight forward direct deduction.

The 6K text file, sudoku.txt (right click and 'Save Link/Target As...'), contains fifty different Su Doku puzzles ranging in difficulty, but all with unique solutions (the first puzzle in the file is the example above).

By solving all fifty puzzles find the sum of the 3-digit numbers found in the top left corner of each solution grid; for example, 483 is the 3-digit number found in the top left corner of the solution grid above.

In [188]:
def check_valid(sudoku,y,x,n):
    if n in sudoku[y]:
        return False
    if n in sudoku[:,x]:
        return False
    if n in sudoku[(y-y%3):(y-y%3+3),(x-x%3):(x-x%3+3)]:
        return False
    return True

In [194]:
def solve(sudoku, count):
    for y in range(9):
        for x in range(9):
            if sudoku[y,x] == 0:
                for n in range(1,10):
                    if check_valid(sudoku,y,x,n):
                        sudoku[y,x] = n
                        if y == 8 and x == 8:
                            solved = sudoku
                        solve(sudoku, count)
                        sudoku[y,x] = 0
                return
    print(sudoku)
    count[0] += int("".join([str(num) for num in sudoku[0, 0:3].tolist()]))

In [195]:
sudoku

array([[4, 0, 3, 0, 2, 0, 6, 0, 0],
       [9, 0, 0, 3, 0, 5, 0, 0, 1],
       [0, 0, 1, 8, 0, 6, 4, 0, 0],
       [0, 0, 8, 1, 0, 2, 9, 0, 0],
       [7, 0, 0, 0, 0, 0, 0, 0, 8],
       [0, 0, 6, 7, 0, 8, 2, 0, 0],
       [0, 0, 2, 6, 0, 9, 5, 0, 0],
       [8, 0, 0, 2, 0, 3, 0, 0, 9],
       [0, 0, 5, 0, 1, 0, 3, 0, 0]])

In [196]:
count = [0]
solve(sudoku, count)
count

[[4 8 3 9 2 1 6 5 7]
 [9 6 7 3 4 5 8 2 1]
 [2 5 1 8 7 6 4 9 3]
 [5 4 8 1 3 2 9 7 6]
 [7 2 9 5 6 4 1 3 8]
 [1 3 6 7 9 8 2 4 5]
 [3 7 2 6 8 9 5 1 4]
 [8 1 4 2 5 3 7 6 9]
 [6 9 5 4 1 7 3 8 2]]


[483]

In [198]:
import numpy as np
import pandas as pd

count = 0
ans = [0]

with open("p096_sudoku.txt") as file:
    sudoku = []
    for lines in file.readlines():
        if count == 9:
            sudoku.append([int(char) for char in lines.strip("\n")])
            sudoku = np.array(sudoku)
            solve(sudoku, ans)
            
            # reset
            count = 0
        elif count == 0:
                        
            sudoku = []
            count += 1
        else:
            sudoku.append([int(char) for char in lines.strip("\n")])
            count += 1
        

[[4 8 3 9 2 1 6 5 7]
 [9 6 7 3 4 5 8 2 1]
 [2 5 1 8 7 6 4 9 3]
 [5 4 8 1 3 2 9 7 6]
 [7 2 9 5 6 4 1 3 8]
 [1 3 6 7 9 8 2 4 5]
 [3 7 2 6 8 9 5 1 4]
 [8 1 4 2 5 3 7 6 9]
 [6 9 5 4 1 7 3 8 2]]
[[2 4 5 9 8 1 3 7 6]
 [1 6 9 2 7 3 5 8 4]
 [8 3 7 5 6 4 2 1 9]
 [9 7 6 1 2 5 4 3 8]
 [5 1 3 4 9 8 6 2 7]
 [4 8 2 7 3 6 9 5 1]
 [3 9 1 6 5 7 8 4 2]
 [7 2 8 3 4 9 1 6 5]
 [6 5 4 8 1 2 7 9 3]]
[[4 6 2 8 3 1 9 5 7]
 [7 9 5 4 2 6 1 8 3]
 [3 8 1 7 9 5 4 2 6]
 [1 7 3 9 8 4 2 6 5]
 [6 5 9 3 1 2 7 4 8]
 [2 4 8 5 6 7 3 1 9]
 [9 2 6 1 7 8 5 3 4]
 [8 3 4 2 5 9 6 7 1]
 [5 1 7 6 4 3 8 9 2]]
[[1 3 7 2 5 6 8 4 9]
 [9 2 8 3 1 4 5 6 7]
 [4 6 5 8 9 7 3 1 2]
 [6 7 3 5 4 2 9 8 1]
 [8 1 9 6 7 3 2 5 4]
 [5 4 2 1 8 9 7 3 6]
 [2 5 6 7 3 1 4 9 8]
 [3 9 1 4 2 8 6 7 5]
 [7 8 4 9 6 5 1 2 3]]
[[5 2 3 8 1 6 7 4 9]
 [7 8 4 5 9 3 1 2 6]
 [6 9 1 4 7 2 8 3 5]
 [2 3 9 1 4 5 6 8 7]
 [4 5 7 2 6 8 9 1 3]
 [1 6 8 9 3 7 2 5 4]
 [3 4 2 7 8 9 5 6 1]
 [9 1 5 6 2 4 3 7 8]
 [8 7 6 3 5 1 4 9 2]]
[[1 7 6 9 2 3 5 8 4]
 [5 2 4 8 1 7 6 3 9]
 [8 9 3 

[[5 8 6 1 2 7 9 4 3]
 [7 2 3 4 6 9 8 5 1]
 [4 9 1 8 5 3 2 6 7]
 [1 3 5 9 7 4 6 2 8]
 [2 7 9 6 1 8 5 3 4]
 [6 4 8 5 3 2 1 7 9]
 [9 1 7 2 4 6 3 8 5]
 [3 5 2 7 8 1 4 9 6]
 [8 6 4 3 9 5 7 1 2]]
[[9 5 4 2 1 3 6 8 7]
 [6 1 7 5 4 8 9 2 3]
 [8 3 2 7 9 6 5 4 1]
 [7 6 3 8 5 1 2 9 4]
 [1 2 8 9 7 4 3 6 5]
 [5 4 9 3 6 2 1 7 8]
 [2 8 1 6 3 7 4 5 9]
 [4 7 5 1 2 9 8 3 6]
 [3 9 6 4 8 5 7 1 2]]
[[1 5 9 7 4 3 8 6 2]
 [2 7 6 5 8 9 4 3 1]
 [3 4 8 6 1 2 7 5 9]
 [6 2 4 9 7 8 3 1 5]
 [9 1 7 2 3 5 6 8 4]
 [5 8 3 1 6 4 2 9 7]
 [4 3 5 8 2 1 9 7 6]
 [8 6 1 4 9 7 5 2 3]
 [7 9 2 3 5 6 1 4 8]]
[[8 6 1 3 5 7 2 9 4]
 [5 9 7 4 8 2 3 6 1]
 [4 3 2 6 1 9 7 8 5]
 [9 1 6 2 7 5 8 4 3]
 [3 5 8 9 6 4 1 2 7]
 [2 7 4 1 3 8 9 5 6]
 [7 8 9 5 4 1 6 3 2]
 [1 4 3 8 2 6 5 7 9]
 [6 2 5 7 9 3 4 1 8]]
[[2 9 4 8 6 3 5 1 7]
 [7 1 5 4 2 9 6 3 8]
 [8 6 3 7 5 1 4 9 2]
 [1 5 2 9 4 7 8 6 3]
 [4 7 9 3 8 6 2 5 1]
 [6 3 8 5 1 2 9 7 4]
 [9 8 6 1 3 4 7 2 5]
 [5 2 1 6 7 8 3 4 9]
 [3 4 7 2 9 5 1 8 6]]
[[3 5 1 2 8 6 4 9 7]
 [4 9 2 1 5 7 6 3 8]
 [7 8 6 

In [199]:
ans

[24702]